### PR TITLE
Ssl additional options

### PR DESCRIPTION
**Pull request by gaborgsomogyi**
If the server is having a self-signed certificate then SSL certificate/host check fails. With these configuration options the checks can be turned off. This problem could happen if somebody created a server but doesn't want to spend money for a signed certificate (verisign or stuff like that).

### CODE REVIEW

**Comment by tananaev** [comment]
There are free and easy to install certificates available (for example, [Let’s Encrypt](https://letsencrypt.org/)), so I don't see any reason for self-signed certificates.

**Comment by gaborgsomogyi** [comment]
The Let's Encrypt certificate authority will not issue certificates for a bare IP address.

**Comment by gaborgsomogyi** [comment]
IP address is static in this case. Spending money for dyndns things also not cheap.

**Comment by tananaev** [comment]
Domain name from a good provider cost less than $10 a year. If you do some search, you can find places where you can get a domain name for free.

**Comment by gaborgsomogyi** [comment]
OK, I'll take a look at it...

**Pull request closed without merging**
