### PR TITLE
Remember me function

### PR DESCRIPTION
**Pull request by gaborgsomogyi**

### CODE REVIEW

**Comment by tananaev** [comment]
Can you please provide some comments.

**Comment by gaborgsomogyi** [comment]
The last used e-mail and password will be loaded when the user is on the login screen and not yet authenticated. The URL is saved and restored but e-mail and password not at the moment.

**Comment by tananaev** [comment]
The only way to get to the login screen is to click "Logout" button. Why would someone click logout just to login with the same credentials?

**Comment by gaborgsomogyi** [comment]
Multiple servers, server config (ip/port,security) changed, user credentials changed on server, etc...

**Comment by tananaev** [comment]
It makes some sense to save an email, but not the password. Having same password on different servers is not very good from security point of view.

**Comment by gaborgsomogyi** [comment]
Yeah, that's true. Maybe we can enable the e-mail loading as a short term solution and in long term some sort of account handling. Hm?

**Comment by tananaev** [comment]
Not sure what you mean by account handling.

Please update your pull request to include only email.

**Comment by tananaev** [comment]
Merged. Thanks.

**Pull request merged**
