### PR TITLE
Command execution

### PR DESCRIPTION
**Pull request by gaborgsomogyi**
In order to execute commands on android.

### CODE REVIEW

**Comment by tananaev** [comment]
If we need to copy model structure from server, we need to use it for everything including positions.

**Comment by gaborgsomogyi** [comment]
All the used model structures are copied from backend. Do you think I've missed something or has to be applied in a different way?

**Comment by tananaev** [comment]
Note that GitHub doesn't send notifications when you push new changes. You need to put a comment to notify me about it.

**Comment by tananaev** [comment]
Merged the changes. Thanks.

**Pull request merged**
